##
## example configuration (version >= 1.2)
##
## 
## if undefine LogDir, Debug mode is forcefully enabled.
LogDir: /home/you/logs/
Debug: false
Daemon: true

## API Key can be defined up to 5-keys with comma separated values.
Prowl:
 APIKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

## IMAP Accounts.
Accounts:
 -
  Application: GMail
  User: yourname
  Pass: password
  Host: imap.gmail.com
  BodyLength: 100
  SubjectLength: 20
  Priority: 0
  Format: "%{subject} from: %{from}"
  Timeout: 7    # Timeout for NoResponse during IDLE. Recommend you set 6-7 for GMail. (in minutes)
 -
  Application: SoftBank
  User: yourname
  Pass: password
  Host: imap.softbank.jp
  BodyLength: 256
  SubjectLength: 20
  Priority: 0
  Format: "Subject:%{subject} From:%{from}"
  NOOPInterval: 20  # NOOP(check) interval with no-IDLE mode. (in seconds)
  NoIDLE: true      # unnecessary, because it should be auto-detected.
  Enable: false     # diable this account. Set true to enable this account.
